name: hr_system

description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  melos: ^7.3.0

workspace:
  - apps/employee
  - apps/hr
  - packages/core
  - packages/data
  - packages/shared_ui