name: core
resolution: workspace
description: "Core Package for All Apps"
version: 0.0.1


environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  theme:
    path: ../../packages/theme
 # Networking
  dio: ^5.9.0

  # Check For Internet
  internet_connection_checker: ^3.0.1

  # Functional programming
  dartz: ^0.10.1

  # Caching
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


